"""empty message

Revision ID: 5f5cb0dd37be
Revises: 91df8b47d02d
Create Date: 2025-02-14 13:46:33.288445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5cb0dd37be'
down_revision = '91df8b47d02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sold_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('product_price', sa.Float(), nullable=False),
    sa.Column('product_image', sa.String(length=255), nullable=True),
    sa.Column('product_category_id', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('date_sold', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sold_items')
    # ### end Alembic commands ###
