"""empty message

Revision ID: 91df8b47d02d
Revises: 3db6eae8b1a4
Create Date: 2025-02-12 02:18:02.821675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91df8b47d02d'
down_revision = '3db6eae8b1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('county',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('subcounty',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('street',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('street',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('subcounty',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('county',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
