version: "3.8"

services:
  # Backend service (Flask app)
  backend:
    build:
      context: .
      dockerfile: ./scripts/backend.dockerfile
    container_name: backend
    environment:
      - FLASK_ENV=production
      - DATABASE_URI=mssql+pyodbc://user:password@db/yourdatabase
      - MPESA_CONSUMER_KEY=your_consumer_key
      - MPESA_CONSUMER_SECRET=your_consumer_secret
      - ENCRYPTION_KEY=your_encryption_key
    ports:
      - "5000:5000"
    depends_on:
      - db

  # Frontend service (Flutter app)
  frontend:
    build:
      context: .
      dockerfile: ./scripts/frontend.dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  # Database service (MSSQL)
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
    driver: local
